services:
  postgres:
    image: postgres:16-alpine
    container_name: frota-core-db
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./frota_pg_data:/var/lib/postgresql/data

volumes:
  frota_pg_data:
